# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae077f95cbf817f9cb9673650786b4ac8907d9f6992b2c5357335bd90a814ae6c19b513c0f4417e43765981f5076d03bcf0213ddc4f6b7cd93a253b2ad55aaeb

test:
  secret_key_base: 0b038d18f2161505e3ee0f051e93e98d329d24a2dab62098f86ed37e3047dc710234d21512bcbe2faf05fcb172ec5fe1b588a186f08f7ea93405da5b4dc3fad7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
